
//Get all robots
GET http://localhost:8800/robot/get HTTP/1.1

###

//Get robots by id
GET http://localhost:8800/robot/get/61a76fe4d2514062e65d7b74 HTTP/1.1

###

//Get lost robots
GET http://localhost:8800/robot/lost HTTP/1.1

###

//Get alive robots
GET http://localhost:8800/robot/alive HTTP/1.1

###